export const ADD_NUMBERS = "ADD_NUMBERS";
export const DIVIDE_NUMBERS = "DIVIDE_NUMBERS";
export const MULTIPLY_NUMBERS = "MULTIPLY_NUMBERS";
export const SUBSTRACT_NUMBERS = "SUBSTRACT_NUMBERS";
export const FIRST_VALUE = "FIRST_VALUE";
export const SECOND_VALUE = "SECOND_VALUE";